apiVersion: apps/v1
kind: Deployment
metadata:
  name: application-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: application-demo
  template:
    metadata:
      labels:
        app: application-demo
    spec:
      containers:
      - name: application-demo
        image: IMAGE
        ports:
        - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: application-demo
spec:
  ports:
  - port: 80
    targetPort: 8080
    name: application-demo
  selector:
    app: application-demo
  type: ClusterIP
